name: double_to_words
description: "A Flutter package to convert numbers, including decimals, into readable words. Ideal for financial, educational, or accessibility-focused applications."
version: 0.0.2
homepage: https://github.com/KasunHasanga/numbersToWords

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
